import { afterAll, beforeAll, expect, test } from 'vitest';
import { launchBrowser, closeBrowser, withInspector } from './fixture.js';
import { seedRuleExplanations, ruleExplanationLink } from './rule-explanation-fixture.js';
import { openRecordedData } from '../ui-navigation.js';
beforeAll(launchBrowser);
afterAll(closeBrowser);

for (const width of [1103, 390]) test(`complete exact rules/questions replace explanation UI and survive real polls at ${width}px`, async () => {
  await withInspector('exact-rule-records', async ({ page, app }) => {
    await page.setViewportSize({ width, height: 1318 });
    await page.locator('.decision-summary').waitFor();
    expect(await page.locator('.recorded-disclosure').getAttribute('open')).toBeNull();
    expect(await page.locator('.rule-question-link, .rule-questions, .question-rich, .rule-outcome, .recorded-rule-facts, .confidence-note').count()).toBe(0);
    expect(await page.locator('.summary-content > details > summary').allTextContents()).toEqual(['Why this assessment', 'Recorded data']);
    await page.locator('.why-disclosure > summary').click();
    expect(await page.locator('.rule-detail').evaluateAll(nodes => nodes.map(node => (node as HTMLElement).dataset.ruleId))).toEqual(['uncertain', 'approval', 'advisory', 'ordinary', 'missing', 'integrity']);
    expect(await page.locator('.rule-detail').count()).toBe(6);
    const firstRule = page.locator('.rule-detail').first();
    await firstRule.evaluate(el => { (el as HTMLElement).dataset.retained = 'same-rule'; });
    expect(await firstRule.locator('.confidence-reading.low-confidence').count()).toBe(2);
    expect(await firstRule.locator('[role=meter]').count()).toBe(2);
    expect(await firstRule.locator('.confidence-values').allTextContents()).toEqual(['PASS 0.88Required 0.9', 'SUFFICIENT 0.85123456789Required 0.9']);
    const whySummary = page.locator('.why-disclosure > summary');
    await whySummary.focus();
    await page.waitForResponse(response => /\/api\/sessions\/[a-f0-9]{64}\/invocations\//.test(response.url()));
    expect(await firstRule.getAttribute('data-retained')).toBe('same-rule');
    expect(await page.evaluate(() => document.activeElement?.parentElement?.classList.contains('why-disclosure'))).toBe(true);
    await openRecordedData(page, 'Questions');
    const query = new URL(app.origin + ruleExplanationLink).searchParams;
    const response = await fetch(`${app.origin}/api/sessions/${query.get('session')}/invocations/${query.get('invocation')}`);
    expect(response.status).toBe(200);
    const retained = (await response.json()).view;
    const exact = page.locator('.exact-rule-data');
    const captured = JSON.parse((await exact.locator('pre').textContent())!);
    expect(captured).toEqual({ questionVersion: retained.questionVersion, rules: retained.rules });
    expect(captured.rules.map((rule: { id: string }) => rule.id)).toEqual(['ordinary', 'uncertain', 'approval', 'advisory', 'missing', 'integrity']);
    const uncertain = captured.rules.find((rule: { id: string }) => rule.id === 'uncertain');
    expect(uncertain.result.outcome.choice).toBe('PASS');
    expect(uncertain.result.outcome.probabilities.PASS).toBe(.88);
    expect(uncertain.result.evidence.choice).toBe('SUFFICIENT');
    expect(uncertain.result.evidence.probabilities).toEqual({ SUFFICIENT: .85123456789, INSUFFICIENT: .14876543211 });
    expect(uncertain.thresholds).toEqual({ effectThreshold: .9, evidenceThreshold: .9 });
    expect(uncertain.gateIds).toContain('outcome-confidence-below-threshold');
    expect(uncertain.gateIds).toContain('evidence-confidence-below-threshold');
    expect(captured.rules.every((rule: { mapping: unknown; questions: { outcome: unknown; evidence: unknown } }) => rule.mapping && rule.questions.outcome && rule.questions.evidence)).toBe(true);
    expect(captured.rules.find((rule: { id: string }) => rule.id === 'missing').gateIds).toBeNull();
    expect(captured.rules.find((rule: { id: string }) => rule.id === 'integrity').builtin).toBe(true);
    expect(await page.locator('.recorded-response').textContent()).toContain('Response truncated');
    expect(await page.locator('.exact-rules').textContent()).toContain('not calibrated safety guarantees');
    expect(await page.locator('.exact-rules script, .exact-rules img, .exact-rules a').count()).toBe(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await exact.evaluate(el => { el.dataset.retained = 'same-node'; el.scrollTop = 83; });
    await exact.focus();
    const outerScroll = await page.locator('.invocation').evaluate(el => el.scrollTop);
    const url = page.url();
    for (let poll = 0; poll < 2; poll++) {
      await page.waitForResponse(response => /\/api\/sessions\/[a-f0-9]{64}\/invocations\//.test(response.url()));
      expect(await exact.getAttribute('data-retained')).toBe('same-node');
      expect(await firstRule.getAttribute('data-retained')).toBe('same-rule');
      expect(await page.locator('.why-disclosure').getAttribute('open')).not.toBeNull();
      expect(await exact.evaluate(el => el.scrollTop)).toBe(83);
      expect(await page.locator('.invocation').evaluate(el => el.scrollTop)).toBe(outerScroll);
      expect(await page.evaluate(() => document.activeElement?.className)).toBe('exact-rule-data');
      expect(await page.locator('.exact-rules').getAttribute('open')).not.toBeNull();
      expect(JSON.parse((await exact.locator('pre').textContent())!)).toEqual(captured);
      expect(page.url()).toBe(url);
    }
  }, { base: false, seed: seedRuleExplanations, path: ruleExplanationLink });
});
