"""Build standalone monitor scripts without executing monitor code."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MODELS = ("apus", "clef")
LOCAL_IMPORT = "from lifecycle import run_monitor\n"


def render(model):
    lifecycle = (ROOT / "lifecycle.py").read_text()
    profile = (ROOT / (model + ".py")).read_text()
    if profile.count(LOCAL_IMPORT) != 1:
        raise ValueError(f"{model}.py must import run_monitor exactly once")
    result = (
        "# Generated by generate.py. Edit lifecycle.py or " + model + ".py, then regenerate.\n"
        + lifecycle.rstrip() + "\n\n\n" + profile.replace(LOCAL_IMPORT, "")
    )
    compile(result, model + "_watch.py", "exec")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stored scripts need regeneration")
    args = parser.parse_args()
    stale = []
    for model in MODELS:
        target = ROOT / (model + "_watch.py")
        expected = render(model)
        if args.check:
            if not target.exists() or target.read_bytes() != expected.encode("utf-8"):
                stale.append(target.name)
        else:
            target.write_bytes(expected.encode("utf-8"))
    if stale:
        parser.exit(1, "Stale monitor scripts: " + ", ".join(stale) + ". Run generate.py.\n")
    print("Monitor scripts are current" if args.check else "Generated standalone monitor scripts")


if __name__ == "__main__":
    main()
