// Exercise the built client against real local HTTP and an offline archive.
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { JSDOM } from 'jsdom';
import { recordFixture } from '../../test/recording-fixture.ts';
import { ArchiveWriter, sessionKey } from '../../src/recording/archive.ts';
import { recordFailureFixture } from '../../test/failure-fixture.ts';
import { startInspector } from '../../src/inspector/server.ts';
import { browserFixture, recordedQuestion } from './browser-fixture.ts';
const directory = await realpath(await mkdtemp(join(tmpdir(), 'tenet-ui-')));
let app, dom, intervals = [];
try {
  const fixture = await recordFixture(directory);
  await browserFixture(directory);
  const writer = new ArchiveWriter({ enabled: true, directory });
  const sink = writer.bind({ sessionId: 's', invocationId: 'incomplete', callId: 'incomplete', toolName: 'edit', mode: 'enforce', cwd: '/historical' });
  sink('begin', { policy: { rules: [{ id: 'old-rule', line: 7, text: 'Historical rule', enforcement: 'BLOCK' }] } });
  sink('decision', { decision: 'BLOCK', reason: 'timeout' });
  sink('response', { preview: '<script>window.hostile=true</script>', truncated: true, bytes: 2000000 });
  await writer.close();
  app = await startInspector({ directory, assets: resolve('inspector/dist') });
  const html = await (await fetch(app.origin)).text();
  const scriptPath = /src="([^"]+\.js)"/.exec(html)?.[1];
  assert.ok(scriptPath);
  const script = await (await fetch(app.origin + scriptPath)).text();
  dom = new JSDOM(html, { url: app.url, runScripts: 'outside-only', pretendToBeVisual: true });
  const nativeSetInterval = dom.window.setInterval.bind(dom.window);
  dom.window.setInterval = (callback, _delay, ...args) => {
    const id = nativeSetInterval(callback, 25, ...args); intervals.push(id); return id;
  };
  const requests = [];
  let failures = 0, fail = false;
  dom.window.fetch = (path, init) => {
    const url = new URL(path, app.origin);
    assert.equal(url.origin, app.origin, 'no external calls');
    requests.push(url.pathname);
    if (failures > 0) { failures--; return Promise.reject(new Error('offline')); }
    assert.equal(init?.headers?.Authorization, undefined);
    return fail ? Promise.resolve(new Response('{}', { status: 503 }))
      : fetch(url, { ...init, headers: { ...init?.headers, Origin: app.origin } });
  };
  dom.window.eval(script);
  const document = dom.window.document;
  async function wait(check) {
    for (let n = 0; n < 100; n++) { if (check()) return; await new Promise(r => setTimeout(r, 20)); }
    throw new Error('UI condition timed out: ' + check.toString() + '\n' + document.body.textContent.slice(0,1600));
  }
  const button = label => [...document.querySelectorAll('button')].find(b => b.textContent.trim() === label);
  const calls = () => [...document.querySelectorAll('[aria-label="Invocations"] button')];
  const chooseCall = async id => {
    calls().find(b => b.querySelector('.call-id')?.textContent === id).click();
    await wait(() => document.querySelector('[aria-label="Invocation detail"] h2')?.textContent.includes(id));
  };
  await wait(() => document.querySelector('[aria-label="Sessions"] button'));
  document.querySelector('[aria-label="Sessions"] button').click();
  await wait(() => calls().length === 12);
  await chooseCall('low-pass');
  assert.match(document.querySelector('[aria-label="Decision explanation"]').textContent, /PASS selected at 0.88; required confidence 0.9/);
  assert.equal(document.querySelector('[aria-label="Pane sizes"]'), null, 'slider toolbar removed');
  assert.equal(document.querySelector('input[type="range"]'), null);
  assert.ok(document.querySelector('.rule-row[aria-pressed="true"] .status-chip.positive')?.textContent.includes('PASS'));
  assert.ok(document.querySelector('.confidence-note')?.textContent.includes('not a reported violation'));
  assert.equal(document.querySelectorAll('.decision-header > details').length, 1, 'one capture-details entry point');
  assert.ok(document.querySelector('.capture-details .lifecycle'), 'lifecycle details are grouped under disclosure');
  assert.ok(document.querySelector('.execution-summary')?.textContent.includes('Execution:'));
  assert.ok(document.querySelector('.gate-details'), 'technical gate identifiers are available on demand');
  assert.equal(document.querySelector('.gate-details').open, false);
  const resize = document.querySelector('[role="separator"][aria-label="Resize assessment pane"]');
  assert.ok(resize);
  assert.equal(resize.getAttribute('aria-orientation'), 'vertical');
  const press = key => resize.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key, bubbles: true }));
  press('End');
  await wait(() => resize.getAttribute('aria-valuenow') === '70');
  press('ArrowRight');
  await wait(() => resize.getAttribute('aria-valuenow') === '70');
  press('Home');
  await wait(() => resize.getAttribute('aria-valuenow') === '35');
  for (let i = 0; i < 18; i++) press('ArrowRight');
  await wait(() => resize.getAttribute('aria-valuenow') === '53');
  resize.parentElement.getBoundingClientRect = () => ({ width: 1000, left: 0 });
  let captured = null;
  resize.setPointerCapture = id => captured = id;
  resize.hasPointerCapture = id => captured === id;
  resize.releasePointerCapture = () => captured = null;
  const pointer = (type, clientX) => {
    const event = new dom.window.MouseEvent(type, { clientX, button: 0, bubbles: true });
    Object.defineProperties(event, { pointerId: { value: 1 }, isPrimary: { value: true } });
    resize.dispatchEvent(event);
  };
  pointer('pointerdown', 100);
  assert.equal(captured, 1);
  pointer('pointermove', 170);
  await wait(() => document.querySelector('.debugger-panes').style.getPropertyValue('--assessment-share') === '60%');
  pointer('pointerup', 170);
  assert.equal(captured, null);
  pointer('pointermove', 500);
  await wait(() => resize.getAttribute('aria-valuenow') === '60');
  pointer('pointerdown', 100); pointer('pointercancel', 100); pointer('pointermove', 500);
  assert.equal(captured, null);
  const cases = [
    ['low-pass', 'Low outcome confidence'], ['unknown', 'Outcome unknown'],
    ['approval', 'Requires approval'], ['evidence', 'Insufficient evidence'],
    ['evidence-confidence', 'Low evidence confidence'], ['warn', 'Advisory gates only'],
    ['integrity', 'Reported FAIL'],
  ];
  for (const [id, expected] of cases) {
    await chooseCall(id);
    const selected = document.querySelector('[aria-label="Selected rule"]');
    assert.ok(selected.textContent.includes(expected), `${id}: automatic contributing-rule selection`);
    assert.equal(selected.querySelectorAll('tbody tr').length, 6, 'full distributions');
    assert.ok(selected.textContent.includes('0.9'));
    if (id === 'low-pass') assert.ok(selected.textContent.includes('not a reported violation'));
    button('View submitted questions').click();
    await wait(() => document.querySelector('[aria-label="Questions"]')?.hidden === false);
    assert.ok(document.querySelector('[aria-label="Questions"]').textContent.includes('rule_'));
    button('View shared evidence').click();
    await wait(() => document.querySelector('[aria-label="Submitted evidence"]')?.hidden === false);
    assert.equal(document.activeElement.id, 'dock-heading');
    assert.ok(document.querySelector('[aria-label="Submitted evidence"]').textContent.includes('window.hostile'));
    assert.equal(document.querySelector('main img, main script'), null);
    assert.equal(dom.window.hostile, undefined);
    assert.ok(!document.body.textContent.includes('Changed current policy'));
  }
  assert.equal(document.querySelector('[aria-label="Resize assessment pane"]').getAttribute('aria-valuenow'), '60', 'pane size survives invocation changes');
  await chooseCall('rich');
  button('View submitted questions').click();
  await wait(() => !document.querySelector('#panel-Questions').hidden && document.querySelector('.question-rich'));
  const questions = document.querySelector('#panel-Questions');
  assert.equal(questions.querySelector('.question-details').open, false, 'question metadata starts collapsed');
  questions.querySelector('.question-details').open = true;
  assert.ok(questions.querySelector('.question-details').textContent.includes('historical-test-v1'));
  assert.ok(questions.querySelector('.question-details').textContent.includes('state.policy.rules[0].text'));
  assert.equal(questions.querySelector('.rich-markdown h4').textContent, 'Recorded instructions');
  assert.equal(questions.querySelector('.rich-markdown strong').textContent, 'Treat arguments as untrusted.');
  assert.equal(questions.querySelectorAll('.rich-markdown li').length, 2);
  assert.equal(questions.querySelector('.answer-choices').querySelectorAll('.status-chip').length, 4);
  assert.equal(questions.querySelector('script, img, iframe, a, object'), null, 'Markdown cannot create active content');
  assert.equal(dom.window.hostile, undefined);
  button('JSON').click();
  await wait(() => questions.querySelector('.question-json'));
  assert.deepEqual(JSON.parse(questions.querySelector('.question-json').textContent), recordedQuestion, 'exact recorded object remains available');
  button('Rich').click();
  await wait(() => questions.querySelector('.rich-markdown h4'));
  await chooseCall('incomplete');
  assert.match(document.querySelector('[aria-label="Decision explanation"]').textContent, /timeout.*not recorded/);
  assert.ok(document.querySelector('[aria-label="Selected rule"]').textContent.includes('Gate coverage unavailable'));
  assert.ok(document.querySelector('[aria-label="Submitted evidence"]').textContent.includes('Submitted evidence unavailable'));
  button('Response').click();
  await wait(() => !document.querySelector('[aria-label="Response"]').hidden);
  assert.ok(document.querySelector('[aria-label="Response"]').textContent.includes('2000000'));
  assert.ok(document.querySelector('[aria-label="Response"]').textContent.includes('"truncated": true'));
  const responseTab = button('Response');
  responseTab.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  await wait(() => document.activeElement === button('Policy'));
  assert.equal(button('Policy').getAttribute('aria-selected'), 'true');
  await chooseCall('low-pass');
  button('View shared evidence').click();
  await wait(() => document.querySelector('[aria-label="Submitted evidence"]')?.hidden === false);
  const evidence = document.querySelector('[aria-label="Submitted evidence"]');
  evidence.scrollTop = 120;
  const pass = [...document.querySelectorAll('[aria-label="Rules"] button')].find(b => b.textContent.includes('Line 2'));
  pass.click();
  await wait(() => document.querySelector('[aria-label="Selected rule"] h3')?.textContent === 'Rule at line 2');
  assert.equal(evidence.scrollTop, 120, 'rule selection preserves shared evidence position');
  assert.equal(document.querySelector('[aria-label="Submitted evidence"]'), evidence, 'shared evidence DOM is stable');
  button('Questions').click();
  await wait(() => document.querySelector('[aria-label="Questions"]')?.hidden === false);
  assert.ok(document.querySelector('[aria-label="Questions"]').textContent.includes('rule_1_outcome'));
  button('Evidence').click();
  await wait(() => !evidence.hidden);
  assert.equal(evidence.scrollTop, 120, 'dock navigation preserves scroll');
  await chooseCall('passing');
  assert.ok(document.querySelector('[aria-label="Decision explanation"]').textContent.includes('No blocking gates'));
  assert.ok(document.querySelector('[aria-label="Invocation detail"]').textContent.includes('executed'));
  button('Calls').click();
  await wait(() => document.querySelector('main').dataset.mobileView === 'calls');
  button('Assessment').click();
  await wait(() => document.querySelector('main').dataset.mobileView === 'assessment');
  assert.ok(document.querySelector('[aria-label="Invocation detail"] h2').textContent.includes('passing'));
  fail = true;
  button('Refresh archive').click();
  await wait(() => document.querySelector('[role="alert"]'));
  assert.ok(document.querySelector('[role="alert"]').textContent.includes('503'));
  fail = false;
  button('Refresh archive').click();
  await wait(() => !document.querySelector('[role="alert"]') && !button('Refresh archive').disabled && document.querySelector('[aria-label="Selected rule"]'));
  await new Promise(resolve => setTimeout(resolve, 20));
  assert.ok(requests.some(p => p.includes('/invocations/')));
  assert.ok(!document.body.textContent.includes('fixture-transport-secret'));
  console.log('PASS: debugger navigation, recorded explanations, full distributions, stable evidence, errors and hostile content.');

  // Upstream live updates, project filtering, deep links and failed-capture coverage.
  const sessionButtons = () => [...document.querySelectorAll('[aria-label="Sessions"] button')];
  const callButtons = () => calls().filter(b => b.querySelector('.call-id'));
  await chooseCall('concerning');
  failures = 3;
  await wait(() => document.querySelector('[role="alert"]')?.textContent.includes('reconnecting automatically'));
  await wait(() => !document.querySelector('[role="alert"]'));
  const selectedRule = document.querySelector('.rule-row[aria-pressed="true"]');
  const selectedRuleText = selectedRule.textContent;
  const shared = document.querySelector('#panel-Evidence'); shared.scrollTop = 37;
  const discovered = new ArchiveWriter({ enabled: true, directory });
  const discoveredSink = discovered.bind({ sessionId: 'live-session', invocationId: 'live-invocation', callId: 'live-call', toolName: 'edit', cwd: '/live-project', mode: 'observe' });
  discoveredSink('begin', {}); discoveredSink('decision', { decision: 'ALLOW', reason: 'all-rules-pass' });
  discoveredSink('permission', { outcome: 'released' }); await discovered.close();
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === 'live-session'));
  assert.equal(document.querySelector('.call-row[aria-pressed="true"] .call-id').textContent, 'concerning');
  const delayed = new ArchiveWriter({ enabled: true, directory });
  const delayedRecord = fixture.records.find(r => r.callId === 'concerning'); assert.ok(delayedRecord);
  delayed.bind({ sessionId: delayedRecord.sessionId, invocationId: delayedRecord.invocationId, callId: delayedRecord.callId, toolName: delayedRecord.toolName, cwd: delayedRecord.cwd, mode: delayedRecord.mode })('execution', { outcome: 'executed', origin: 'pi-tool-result' });
  await delayed.close();
  await wait(() => document.querySelector('.lifecycle').textContent.includes('executed'));
  assert.equal(document.querySelector('.rule-row[aria-pressed="true"]').textContent, selectedRuleText);
  assert.equal(document.querySelector('#panel-Evidence'), shared); assert.equal(shared.scrollTop, 37);
  assert.ok(document.body.textContent.includes('rule-fail'));
  const pages = new ArchiveWriter({ enabled: true, directory }), arbitrary = '../雪 ?#%';
  for (let n = 0; n < 55; n++) pages.bind({ sessionId: arbitrary, invocationId: `page-${n}`, callId: 'reused', toolName: 'edit', cwd: '/second-project', mode: 'observe' })('begin', {});
  pages.bind({ sessionId: 'fork', invocationId: 'fork-call', callId: 'reused', toolName: 'edit', cwd: '/third-project', mode: 'observe' })('begin', {});
  await pages.close();
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === arbitrary));
  const filter = document.querySelector('input[aria-label="Project directory"]'); assert.ok(filter);
  filter.value = '/second-project'; filter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  await wait(() => !button('Filter projects').disabled); button('Filter projects').click();
  await wait(() => sessionButtons().length === 1);
  sessionButtons()[0].click(); await wait(() => button('More invocations'));
  assert.equal(callButtons().length, 50); callButtons()[0].click();
  await wait(() => document.querySelector('.decision-title h2')?.textContent.includes('reused'));
  const selectedLink = dom.window.location.href;
  assert.equal(new URL(selectedLink).searchParams.get('session'), sessionKey(arbitrary));
  assert.match(new URL(selectedLink).searchParams.get('invocation'), /^[a-f0-9]{64}$/);
  assert.ok(!selectedLink.includes('window.hostile'));
  button('More invocations').click(); await wait(() => callButtons().length === 55);
  assert.equal(dom.window.location.href, selectedLink);
  const beforePoll = requests.length; await wait(() => requests.length >= beforePoll + 6);
  assert.equal(callButtons().length, 55, 'polling preserves loaded pages');
  assert.equal(sessionButtons().length, 1, 'polling preserves project filter');
  assert.equal(dom.window.location.href, selectedLink, 'polling preserves deep link');
  dom.window.history.replaceState(null, '', `/?session=${sessionKey(arbitrary)}&invocation=${sessionKey('page-0')}`);
  dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => document.querySelector('.invocation')?.textContent.includes('page-0'));
  assert.ok(document.querySelector('.invocation').textContent.includes(arbitrary));
  dom.window.history.replaceState(null, '', '/?session=../../unsafe&invocation=bad');
  dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => document.querySelector('[role="alert"]')?.textContent.includes('Invalid'));
  dom.window.history.replaceState(null, '', '/'); dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => !document.querySelector('[role="alert"]'));
  filter.value = '/no-recordings'; filter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  button('Filter projects').click(); await wait(() => document.body.textContent.includes('No recorded sessions for this project.'));
  button('All projects').click(); await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === arbitrary));
  const linked = new JSDOM(html, { url: `${app.origin}/?session=${sessionKey(arbitrary)}&invocation=${sessionKey('page-0')}`, runScripts: 'outside-only', pretendToBeVisual: true });
  try {
    linked.window.fetch = dom.window.fetch; linked.window.eval(script);
    for (let n = 0; n < 100 && !linked.window.document.querySelector('.invocation'); n++) await new Promise(r => setTimeout(r, 20));
    assert.ok(linked.window.document.querySelector('.invocation').textContent.includes('page-0'), 'fresh launch restores deep-linked call beyond first page');
  } finally { linked.window.close(); }
  await recordFailureFixture(directory); await app.close();
  app = await startInspector({ directory, assets: resolve('inspector/dist') });
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === 'failure-history'));
  sessionButtons().find(b => b.querySelector('strong')?.textContent === 'failure-history').click();
  await wait(() => callButtons().some(b => b.textContent.includes('missing-credentials')));
  for (const reason of ['temporary-record', 'corrupt-record', 'unsupported-schema']) assert.ok(document.body.textContent.includes(reason));
  assert.ok(document.body.textContent.includes('Writer-wide capture health'));
  for (const kind of ['missing-credentials', 'provider-error', 'invalid-response', 'interrupted', 'truncated-response', 'unavailable-response', 'missing-payload', 'capture-loss']) {
    await chooseCall(kind); const detail = document.querySelector('.invocation').textContent;
    if (kind === 'interrupted' || kind === 'capture-loss') {
      assert.ok(detail.includes('Assessment incomplete')); assert.ok(detail.includes('unknown'));
      assert.ok(![...document.querySelectorAll('.rule-row .status-chip')].some(el => el.textContent === 'PASS'));
    } else assert.ok(detail.includes('Assessment failed'));
    if (kind === 'missing-credentials') assert.ok(detail.includes('not submitted'));
    if (kind === 'missing-payload') assert.ok(detail.includes('submitted; payload unavailable'));
    if (kind === 'truncated-response') assert.ok(detail.includes('Response truncated'));
    if (kind === 'unavailable-response') assert.ok(detail.includes('Response snapshot unavailable'));
    assert.equal(dom.window.hostile, undefined); assert.equal(document.querySelector('.invocation script'), null);
  }
  assert.ok(!document.body.textContent.includes('fixture-transport-secret'));
  console.log('PASS: live discovery, delayed execution, preserved selection, project filters, pagination, deep links, reconnect and failed capture history.');
} finally {
  for (const id of intervals) dom?.window.clearInterval(id);
  await new Promise(resolve => setTimeout(resolve, 50));
  dom?.window.close(); await app?.close(); await rm(directory, { recursive: true, force: true });
}
