// Exercise the built client against real local HTTP and an offline archive.
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { JSDOM } from 'jsdom';
import { recordFixture } from '../../test/recording-fixture.ts';
import { sessionKey, qualifiedSessionKey } from '../../src/recording/archive.ts';
import { ArchiveWriter } from '../../test/legacy-recording-fixture.ts';
import { recordFailureFixture } from '../../test/failure-fixture.ts';
import { startInspector } from '../../src/inspector/server.ts';
import { browserFixture, recordedQuestion } from './browser-fixture.ts';
const directory = await realpath(await mkdtemp(join(tmpdir(), 'tenet-ui-')));
let app, dom, intervals = [];
try {
  const fixture = await recordFixture(directory);
  await browserFixture(directory);
  const writer = new ArchiveWriter({ enabled: true, directory });
  const sink = writer.bind({ host: 'pi', contextId: 'main', sessionId: 's', invocationId: 'incomplete', callId: 'incomplete', toolName: 'edit', mode: 'enforce', cwd: '/historical' });
  sink('begin', { policy: { rules: [{ id: 'old-rule', line: 7, text: 'Historical rule', enforcement: 'BLOCK' }] } });
  sink('decision', { decision: 'BLOCK', reason: 'timeout' });
  sink('response', { preview: '<script>window.hostile=true</script>', truncated: true, bytes: 2000000 });
  await writer.close();
  // The archive-wide response sees this warning; the selected session does not.
  const unrelatedDirectory = join(directory, sessionKey('unrelated-session'));
  await mkdir(unrelatedDirectory, { mode: 0o700 });
  await writeFile(join(unrelatedDirectory, 'pending.tmp'), 'in progress', { mode: 0o600 });
  app = await startInspector({ directory, assets: resolve('inspector/dist') });
  const html = await (await fetch(app.origin)).text();
  const scriptPath = /src="([^"]+\.js)"/.exec(html)?.[1];
  assert.ok(scriptPath);
  const script = await (await fetch(app.origin + scriptPath)).text();
  dom = new JSDOM(html, { url: app.url, runScripts: 'outside-only', pretendToBeVisual: true });
  const nativeSetInterval = dom.window.setInterval.bind(dom.window);
  dom.window.setInterval = (callback, _delay, ...args) => {
    const id = nativeSetInterval(callback, 25, ...args); intervals.push(id); return id;
  };
  const requests = [];
  let failures = 0, fail = false;
  dom.window.fetch = (path, init) => {
    const url = new URL(path, app.origin);
    assert.equal(url.origin, app.origin, 'no external calls');
    requests.push(url.pathname);
    if (failures > 0) { failures--; return Promise.reject(new Error('offline')); }
    assert.equal(init?.headers?.Authorization, undefined);
    return fail ? Promise.resolve(new Response('{}', { status: 503 }))
      : fetch(url, { ...init, headers: { ...init?.headers, Origin: app.origin } });
  };
  dom.window.eval(script);
  const document = dom.window.document;
  async function wait(check) {
    for (let n = 0; n < 100; n++) { if (check()) return; await new Promise(r => setTimeout(r, 20)); }
    throw new Error('UI condition timed out: ' + check.toString() + '\n' + document.body.textContent.slice(0,1600));
  }
  const button = label => [...document.querySelectorAll('button')].find(b => b.textContent.trim() === label);
  const calls = () => [...document.querySelectorAll('[aria-label="Invocations"] button')];
  const chooseCall = async id => {
    await wait(() => calls().some(b => b.querySelector('.call-id')?.textContent === id));
    calls().find(b => b.querySelector('.call-id')?.textContent === id).click();
    await wait(() => document.querySelector('[aria-label="Invocation detail"] h2 span')?.textContent === id);
  };
  await wait(() => document.querySelector('[aria-label="Sessions"] button'));
  await wait(() => document.querySelector('[aria-label="Invocation detail"]'));
  assert.equal(document.querySelector('.call-row[aria-pressed="true"]'), calls()[0], 'fresh visits open the latest call');
  document.querySelector('[aria-label="Sessions"] button').click();
  await wait(() => calls().length === 13);
  await chooseCall('low-pass');
  const decisionSymbols = [];
  for (const state of ['positive', 'danger', 'approval']) {
    const badge = document.querySelector(`.call-state .status-chip.${state}`);
    assert.ok(badge, `sidebar includes ${state} decisions`);
    const symbol = badge.querySelector('svg[aria-hidden="true"]');
    assert.ok(symbol, `${state} decisions have a shape cue as well as color and text`);
    decisionSymbols.push(symbol.innerHTML);
  }
  assert.equal(new Set(decisionSymbols).size, 3, 'allow, block and approval use distinct symbols');
  const observedBadge = calls().find(row => row.querySelector('.call-id')?.textContent === 'summary').querySelector('.status-chip');
  assert.equal(observedBadge.textContent.trim(), 'Would block', 'observation is not mislabeled as actual blocking');
  assert.ok(document.querySelector('[aria-label="Decision summary"]'), 'a visual summary leads the selected call');
  const map = document.querySelector('[aria-label="Decision map"]');
  assert.ok(map, 'the selected call exposes a recorded decision map');
  assert.match(map.textContent, /Rule outcome.*PASS/s, 'a confidence gate does not turn PASS into a violation');
  const inspectConfidence = document.querySelector('button[aria-label="Inspect outcome confidence"]');
  assert.ok(inspectConfidence, 'recorded gates are keyboard-operable inspection controls');
  inspectConfidence.click();
  await wait(() => document.querySelector('.rule-inspection')?.open);
  assert.equal(document.querySelector('.evidence-disclosure').open, false, 'raw evidence starts collapsed');
  assert.equal(document.querySelector('.rule-technical').open, false, 'probability tables start collapsed');
  assert.equal(document.querySelector('.other-rules').open, false, 'other rules start collapsed');
  assert.equal(document.querySelector('[role="meter"]').getAttribute('aria-valuenow'), '0.88');
  assert.match(document.querySelector('[role="meter"]').getAttribute('aria-valuetext'), /0.88.*0.9/);
  assert.match(document.querySelector('[aria-label="Decision explanation"]').textContent, /PASS selected at 0.88; required confidence 0.9/);
  assert.equal(document.querySelector('[aria-label="Pane sizes"]'), null, 'slider toolbar removed');
  assert.equal(document.querySelector('input[type="range"]'), null);
  assert.equal(document.querySelector('[aria-label="Recording issues"]'), null, 'selected session has no recording warning');
  const allSessions = await (await fetch(app.origin + '/api/sessions')).json();
  assert.ok(allSessions.issues.some(issue => issue.reason === 'temporary-record'), 'other-session warning remains recorded');
  const stableDetail = document.querySelector('.invocation');
  const stableMutations = [];
  const observer = new dom.window.MutationObserver(records => stableMutations.push(...records));
  observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true });
  const stableRequests = requests.length;
  await wait(() => requests.length >= stableRequests + 6);
  observer.disconnect();
  assert.equal(document.querySelector('.invocation'), stableDetail, 'unchanged polling keeps the selected detail mounted');
  const picker = document.querySelector('.session-picker');
  picker.open = true;
  const pickerFilter = document.querySelector('input[aria-label="Project directory"]');
  pickerFilter.focus(); pickerFilter.value = '/histor';
  pickerFilter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  const pickerRequests = requests.length;
  await wait(() => requests.length >= pickerRequests + 6);
  await new Promise(resolve => setTimeout(resolve, 30));
  assert.equal(picker.open, true, 'refresh leaves an opened session picker open');
  assert.equal(document.activeElement, pickerFilter, 'refresh retains project search focus');
  assert.equal(pickerFilter.value, '/histor', 'refresh retains unfinished project search');
  picker.open = false;
  assert.equal(stableMutations.length, 0, `unchanged polling does not flash the page: ${stableMutations.map(r => `${r.type} ${r.target.nodeName}.${r.attributeName ?? ''}`).join(', ')}`);
  assert.ok(document.querySelector('.rule-row[aria-pressed="true"] .status-chip.positive')?.textContent.includes('PASS'));
  assert.ok(document.querySelector('.confidence-note')?.textContent.includes('not a reported violation'));
  assert.equal(document.querySelectorAll('.capture-details').length, 1, 'one recording-details entry point');
  assert.ok(document.querySelector('.capture-details .lifecycle'), 'lifecycle details are grouped under disclosure');
  assert.ok(document.querySelector('.execution-summary')?.textContent.includes('record'));
  assert.ok(document.querySelector('.gate-details'), 'technical gate identifiers are available on demand');
  assert.equal(document.querySelector('.gate-details').open, false);
  assert.equal(document.querySelector('[role="separator"][aria-label="Resize assessment pane"]'), null, 'no split evidence pane');
  assert.ok(document.querySelector('.app-bar .session-picker'), 'sessions remain accessible from the toolbar');
  assert.ok(document.querySelector('.explorer h2:not(.visually-hidden)'), 'the sidebar has a visible Recent calls heading');
  const resize = document.querySelector('[aria-label="Resize call explorer"]');
  assert.ok(resize, 'the call sidebar can be resized without changing the decision map');
  resize.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'End', bubbles: true }));
  await wait(() => resize.getAttribute('aria-valuenow') === '460');
  const cases = [
    ['low-pass', 'Outcome confidence'], ['unknown', 'Outcome unknown'],
    ['approval', 'Requires approval'], ['evidence', 'Insufficient evidence'],
    ['evidence-confidence', 'Evidence confidence'], ['warn', 'Advisory gates only'],
    ['integrity', 'Reported FAIL'],
  ];
  for (const [id, expected] of cases) {
    await chooseCall(id);
    const selected = document.querySelector('[aria-label="Selected rule"]');
    assert.ok(selected.textContent.includes(expected), `${id}: automatic contributing-rule selection`);
    assert.equal(selected.querySelectorAll('tbody tr').length, 6, 'full distributions');
    assert.ok(selected.textContent.includes('0.9'));
    if (id === 'low-pass') assert.ok(selected.textContent.includes('not a reported violation'));
    if (id === 'unknown') assert.match(document.querySelector('.map-check').textContent, /does not mean passed/, 'UNKNOWN is never drawn as a successful outcome');
    if (id === 'warn') assert.equal(document.querySelectorAll('.map-edge.blocking').length, 0, 'WARN findings are not blocking contributions');
    button('View submitted questions').click();
    await wait(() => document.querySelector('[aria-label="Questions"]')?.hidden === false);
    assert.ok(document.querySelector('[aria-label="Questions"]').textContent.includes('rule_'));
    button('View shared evidence').click();
    await wait(() => document.querySelector('[aria-label="Submitted evidence"]')?.hidden === false);
    assert.equal(document.activeElement.id, 'dock-heading');
    assert.ok(document.querySelector('[aria-label="Submitted evidence"]').textContent.includes('window.hostile'));
    assert.equal(document.querySelector('main img, main script'), null);
    assert.equal(dom.window.hostile, undefined);
    assert.ok(!document.body.textContent.includes('Changed current policy'));
  }
  assert.equal(resize.getAttribute('aria-valuenow'), '460', 'sidebar size survives invocation changes');
  await chooseCall('summary');
  assert.match(document.querySelector('.summary-reason').textContent, /Evidence confidence was below/);
  assert.match(document.querySelector('.execution-summary').textContent, /call ran.*Observe mode/);
  assert.equal(document.querySelector('[aria-label="Recorded action"]').textContent, 'git status --short && git diff -- README.md && git diff --cached --stat');
  assert.equal(document.querySelector('[role="meter"]').getAttribute('aria-valuenow'), '0.85');
  assert.equal(document.querySelector('.evidence-disclosure').open, false);
  await chooseCall('rich');
  button('View submitted questions').click();
  await wait(() => !document.querySelector('#panel-Questions').hidden && document.querySelector('.question-rich'));
  const questions = document.querySelector('#panel-Questions');
  assert.equal(questions.querySelector('.question-details').open, false, 'question metadata starts collapsed');
  questions.querySelector('.question-details').open = true;
  assert.ok(questions.querySelector('.question-details').textContent.includes('historical-test-v1'));
  assert.ok(questions.querySelector('.question-details').textContent.includes('state.policy.rules[0].text'));
  assert.equal(questions.querySelector('.rich-markdown h4').textContent, 'Recorded instructions');
  assert.equal(questions.querySelector('.rich-markdown strong').textContent, 'Treat arguments as untrusted.');
  assert.equal(questions.querySelectorAll('.rich-markdown li').length, 2);
  assert.equal(questions.querySelector('.answer-choices').querySelectorAll('.status-chip').length, 4);
  assert.equal(questions.querySelector('script, img, iframe, a, object'), null, 'Markdown cannot create active content');
  assert.equal(dom.window.hostile, undefined);
  button('JSON').click();
  await wait(() => questions.querySelector('.question-json'));
  assert.deepEqual(JSON.parse(questions.querySelector('.question-json').textContent), recordedQuestion, 'exact recorded object remains available');
  button('Rich').click();
  await wait(() => questions.querySelector('.rich-markdown h4'));
  await chooseCall('incomplete');
  assert.match(document.querySelector('[aria-label="Decision explanation"]').textContent, /timeout.*not recorded/);
  assert.ok(document.querySelector('[aria-label="Selected rule"]').textContent.includes('Gate coverage unavailable'));
  assert.ok(document.querySelector('[aria-label="Submitted evidence"]').textContent.includes('Submitted evidence unavailable'));
  button('Response').click();
  await wait(() => !document.querySelector('[aria-label="Response"]').hidden);
  assert.ok(document.querySelector('[aria-label="Response"]').textContent.includes('2000000'));
  assert.ok(document.querySelector('[aria-label="Response"]').textContent.includes('"truncated": true'));
  const responseTab = button('Response');
  responseTab.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  await wait(() => document.activeElement === button('Policy'));
  assert.equal(button('Policy').getAttribute('aria-selected'), 'true');
  await chooseCall('low-pass');
  button('View shared evidence').click();
  await wait(() => document.querySelector('[aria-label="Submitted evidence"]')?.hidden === false);
  const evidence = document.querySelector('[aria-label="Submitted evidence"]');
  evidence.scrollTop = 120;
  const pass = [...document.querySelectorAll('[aria-label="Rules"] button')].find(b => b.textContent.includes('Line 2'));
  pass.click();
  await wait(() => document.querySelector('[aria-label="Selected rule"] h3')?.textContent === 'Rule at line 2');
  assert.equal(evidence.scrollTop, 120, 'rule selection preserves shared evidence position');
  assert.equal(document.querySelector('[aria-label="Submitted evidence"]'), evidence, 'shared evidence DOM is stable');
  button('Questions').click();
  await wait(() => document.querySelector('[aria-label="Questions"]')?.hidden === false);
  assert.ok(document.querySelector('[aria-label="Questions"]').textContent.includes('rule_1_outcome'));
  button('Evidence').click();
  await wait(() => !evidence.hidden);
  assert.equal(evidence.scrollTop, 120, 'dock navigation preserves scroll');
  await chooseCall('passing');
  assert.ok(document.querySelector('[aria-label="Decision explanation"]').textContent.includes('No blocking gates'));
  assert.ok(document.querySelector('[aria-label="Invocation detail"]').textContent.includes('executed'));
  button('Calls').click();
  await wait(() => document.querySelector('main').dataset.mobileView === 'calls');
  button('Summary').click();
  await wait(() => document.querySelector('main').dataset.mobileView === 'assessment');
  assert.ok(document.querySelector('[aria-label="Invocation detail"] h2').textContent.includes('passing'));
  fail = true;
  button('Refresh archive').click();
  await wait(() => document.querySelector('[role="alert"]'));
  assert.ok(document.querySelector('[role="alert"]').textContent.includes('503'));
  fail = false;
  button('Refresh archive').click();
  await wait(() => !document.querySelector('[role="alert"]') && !button('Refresh archive').disabled && document.querySelector('[aria-label="Selected rule"]'));
  await new Promise(resolve => setTimeout(resolve, 20));
  assert.ok(requests.some(p => p.includes('/invocations/')));
  assert.ok(!document.body.textContent.includes('fixture-transport-secret'));
  console.log('PASS: debugger navigation, recorded explanations, full distributions, stable evidence, errors and hostile content.');

  // Upstream live updates, project filtering, deep links and failed-capture coverage.
  const sessionButtons = () => [...document.querySelectorAll('[aria-label="Sessions"] button')];
  const callButtons = () => calls().filter(b => b.querySelector('.call-id'));
  await chooseCall('concerning');
  failures = 3;
  await wait(() => document.querySelector('[role="alert"]')?.textContent.includes('reconnecting automatically'));
  await wait(() => !document.querySelector('[role="alert"]'));
  const selectedRule = document.querySelector('.rule-row[aria-pressed="true"]');
  const selectedRuleText = selectedRule.textContent;
  const shared = document.querySelector('#panel-Evidence'); shared.scrollTop = 37;
  const discovered = new ArchiveWriter({ enabled: true, directory });
  picker.open = true;
  const discoveredSink = discovered.bind({ sessionId: 'live-session', invocationId: 'live-invocation', callId: 'live-call', toolName: 'edit', cwd: '/live-project', mode: 'observe' });
  discoveredSink('begin', {}); discoveredSink('decision', { decision: 'ALLOW', reason: 'all-rules-pass' });
  discoveredSink('permission', { outcome: 'released' }); await discovered.close();
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === 'live-session'));
  assert.equal(picker.open, true, 'discovering another session does not close the open switcher');
  picker.open = false;
  assert.equal(document.querySelector('.call-row[aria-pressed="true"] .call-id').textContent, 'concerning');
  const delayed = new ArchiveWriter({ enabled: true, directory });
  const delayedRecord = fixture.records.find(r => r.callId === 'concerning'); assert.ok(delayedRecord);
  delayed.bind({ host: delayedRecord.host, contextId: delayedRecord.contextId, sessionId: delayedRecord.sessionId, invocationId: delayedRecord.invocationId, callId: delayedRecord.callId, toolName: delayedRecord.toolName, cwd: delayedRecord.cwd, mode: delayedRecord.mode })('execution', { outcome: 'executed', origin: 'pi-tool-result' });
  await delayed.close();
  await wait(() => document.querySelector('.lifecycle').textContent.includes('executed'));
  assert.equal(document.querySelector('.rule-row[aria-pressed="true"]').textContent, selectedRuleText);
  assert.equal(document.querySelector('#panel-Evidence'), shared); assert.equal(shared.scrollTop, 37);
  assert.ok(document.body.textContent.includes('rule-fail'));
  const pages = new ArchiveWriter({ enabled: true, directory }), arbitrary = '../雪 ?#%';
  for (let n = 0; n < 55; n++) pages.bind({ sessionId: arbitrary, invocationId: `page-${n}`, callId: 'reused', toolName: 'edit', cwd: '/second-project', mode: 'observe' })('begin', {});
  pages.bind({ sessionId: 'fork', invocationId: 'fork-call', callId: 'reused', toolName: 'edit', cwd: '/third-project', mode: 'observe' })('begin', {});
  await pages.close();
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === arbitrary));
  const filter = document.querySelector('input[aria-label="Project directory"]'); assert.ok(filter);
  filter.value = '/second-project'; filter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  picker.open = true;
  const initialPicker = picker;
  await wait(() => !button('Filter projects').disabled); button('Filter projects').click();
  await wait(() => sessionButtons().length === 1);
  assert.equal(initialPicker.open, true, 'filtering keeps the session switcher open for choosing a result');
  sessionButtons()[0].click(); await wait(() => button('More invocations'));
  assert.equal(picker.open, false, 'choosing a session closes the switcher');
  assert.equal(callButtons().length, 50); callButtons()[0].click();
  await wait(() => document.querySelector('.decision-title h2')?.textContent.includes('reused'));
  const selectedLink = dom.window.location.href;
  assert.equal(new URL(selectedLink).searchParams.get('session'), sessionKey(arbitrary));
  assert.match(new URL(selectedLink).searchParams.get('invocation'), /^[a-f0-9]{64}$/);
  assert.ok(!selectedLink.includes('window.hostile'));
  button('More invocations').click(); await wait(() => callButtons().length === 55);
  assert.equal(dom.window.location.href, selectedLink);
  const beforePoll = requests.length; await wait(() => requests.length >= beforePoll + 6);
  assert.equal(callButtons().length, 55, 'polling preserves loaded pages');
  assert.equal(sessionButtons().length, 1, 'polling preserves project filter');
  assert.equal(dom.window.location.href, selectedLink, 'polling preserves deep link');
  dom.window.history.replaceState(null, '', `/?session=${sessionKey(arbitrary)}&invocation=${sessionKey('page-0')}`);
  dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => document.querySelector('.invocation')?.textContent.includes('page-0'));
  assert.ok(document.querySelector('.invocation').textContent.includes(arbitrary));
  dom.window.history.replaceState(null, '', '/?session=../../unsafe&invocation=bad');
  dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => document.querySelector('[role="alert"]')?.textContent.includes('Invalid'));
  dom.window.history.replaceState(null, '', '/'); dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));
  await wait(() => !document.querySelector('[role="alert"]'));
  filter.value = '/no-recordings'; filter.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  button('Filter projects').click(); await wait(() => document.body.textContent.includes('No recorded sessions for this project.'));
  picker.open = true;
  button('All projects').click();
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === arbitrary));
  assert.equal(picker.open, true, 'clearing the filter keeps the switcher open when no session is selected');
  const linked = new JSDOM(html, { url: `${app.origin}/?session=${sessionKey(arbitrary)}&invocation=${sessionKey('page-0')}`, runScripts: 'outside-only', pretendToBeVisual: true });
  try {
    linked.window.fetch = dom.window.fetch; linked.window.eval(script);
    for (let n = 0; n < 100 && !linked.window.document.querySelector('.invocation'); n++) await new Promise(r => setTimeout(r, 20));
    assert.ok(linked.window.document.querySelector('.invocation').textContent.includes('page-0'), 'fresh launch restores deep-linked call beyond first page');
  } finally { linked.window.close(); }
  const emptyKey = sessionKey('not-yet-recorded');
  const empty = new JSDOM(html, { url: `${app.origin}/?session=${emptyKey}`, runScripts: 'outside-only', pretendToBeVisual: true });
  try {
    empty.window.setInterval = () => 0; // This secondary view tests navigation, not polling.
    empty.window.fetch = dom.window.fetch; empty.window.eval(script);
    for (let n = 0; n < 100 && !empty.window.document.body.textContent.includes('Waiting for recorded calls'); n++) await new Promise(r => setTimeout(r, 20));
    assert.equal(new URL(empty.window.location.href).searchParams.get('session'), emptyKey);
    assert.match(empty.window.document.querySelector('.empty-state h2').textContent, /Waiting for recorded calls/);
    assert.equal(empty.window.document.querySelector('.call-row[aria-pressed="true"]'), null, 'an unrelated call must not be selected');
    assert.equal(empty.window.document.querySelector('.session-picker summary').textContent.trim(), 'Selected session');
    const other = [...empty.window.document.querySelectorAll('[aria-label="Sessions"] button')].find(b => b.querySelector('strong')?.textContent === 'live-session');
    assert.ok(other, 'another project remains browsable');
    other.click();
    for (let n = 0; n < 100 && !empty.window.document.querySelector('.invocation'); n++) await new Promise(r => setTimeout(r, 20));
    assert.equal(new URL(empty.window.location.href).searchParams.get('session'), sessionKey('live-session'));
  } finally { empty.window.close(); }
  await recordFailureFixture(directory); await app.close();
  app = await startInspector({ directory, assets: resolve('inspector/dist') });
  await wait(() => sessionButtons().some(b => b.querySelector('strong')?.textContent === 'failure-history'));
  sessionButtons().find(b => b.querySelector('strong')?.textContent === 'failure-history').click();
  await wait(() => callButtons().some(b => b.textContent.includes('missing-credentials')));
  for (const reason of ['temporary-record', 'corrupt-record', 'unsupported-schema']) assert.ok(document.body.textContent.includes(reason));
  assert.ok(document.body.textContent.includes('Writer-wide capture health'));
  for (const kind of ['missing-credentials', 'provider-error', 'invalid-response', 'interrupted', 'truncated-response', 'unavailable-response', 'missing-payload', 'capture-loss']) {
    await chooseCall(kind); const detail = document.querySelector('.invocation').textContent;
    if (kind === 'interrupted' || kind === 'capture-loss') {
      assert.ok(detail.includes('Assessment incomplete')); assert.ok(detail.includes('unknown'));
      assert.ok(![...document.querySelectorAll('.rule-row .status-chip')].some(el => el.textContent === 'PASS'));
    } else assert.ok(detail.includes('Assessment failed'));
    if (kind === 'missing-credentials') assert.ok(detail.includes('not submitted'));
    if (kind === 'missing-payload') assert.ok(detail.includes('submitted; payload unavailable'));
    if (kind === 'truncated-response') assert.ok(detail.includes('Response truncated'));
    if (kind === 'unavailable-response') assert.ok(detail.includes('Response snapshot unavailable'));
    assert.equal(dom.window.hostile, undefined); assert.equal(document.querySelector('.invocation script'), null);
  }
  assert.ok(!document.body.textContent.includes('fixture-transport-secret'));
  const mixed = new ArchiveWriter({ enabled: true, directory });
  const claude = mixed.bind({ host: 'claude-code', contextId: 'child', sessionId: 'live-session', invocationId: 'mixed-invocation', callId: 'mixed-call', toolName: 'Bash', cwd: '/historical', mode: 'observe' });
  claude('begin', { adapterCoverage: { version: null, limitations: ['actual-host-unverified', 'approval-unavailable'] } });
  claude('decision', { decision: 'ALLOW', reason: 'all-rules-pass' });
  claude('permission', { outcome: 'released' });
  await mixed.close();
  await wait(() => sessionButtons().some(b => b.textContent.includes('claude-code / child')));
  sessionButtons().find(b => b.textContent.includes('claude-code / child')).click();
  await wait(() => document.querySelector('.decision-summary')?.textContent.includes('claude-code / child'));
  assert.equal(new URL(dom.window.location.href).searchParams.get('session'), qualifiedSessionKey('claude-code', 'live-session', 'child'));
  assert.match(document.querySelector('.map-notices').textContent, /actual-host-unverified/);
  const mixedDetails = document.querySelector('.capture-details'); mixedDetails.open = true;
  assert.match(mixedDetails.textContent, /Would decide.*ALLOW.*Permission.*released.*Execution.*unknown/s);
  assert.match(mixedDetails.textContent, /Host coverage limitations.*approval-unavailable/s);
  console.log('PASS: live discovery, delayed execution, preserved selection, project filters, pagination, deep links, reconnect and failed capture history.');

  // A deep-linked session can have recordings even when the first picker page omits it.
  const pagedDirectory = await realpath(await mkdtemp(join(tmpdir(), 'tenet-paged-link-')));
  let pagedApp, pagedDom;
  try {
    const pagedWriter = new ArchiveWriter({ enabled: true, directory: pagedDirectory });
    pagedWriter.bind({ sessionId: 'older-session', invocationId: 'older-call', callId: 'older-call', toolName: 'read', mode: 'observe', cwd: '/old-project' })('begin', {});
    await new Promise(resolve => setTimeout(resolve, 20));
    for (let n = 0; n < 52; n++) pagedWriter.bind({ sessionId: `new-${n}`, invocationId: `new-${n}`, callId: `new-${n}`, toolName: 'read', mode: 'observe', cwd: '/new-project' })('begin', {});
    await pagedWriter.close();
    pagedApp = await startInspector({ directory: pagedDirectory, assets: resolve('inspector/dist') });
    const page = await (await fetch(pagedApp.origin + '/api/sessions')).json();
    assert.equal(page.sessions.length, 50);
    assert.ok(!page.sessions.some(item => item.sessionId === 'older-session'));
    pagedDom = new JSDOM(html, { url: `${pagedApp.origin}/?session=${sessionKey('older-session')}`, runScripts: 'outside-only', pretendToBeVisual: true });
    pagedDom.window.setInterval = () => 0;
    pagedDom.window.fetch = (path, init) => fetch(new URL(path, pagedApp.origin), { ...init, headers: { Origin: pagedApp.origin } });
    pagedDom.window.eval(script);
    for (let n = 0; n < 100 && !pagedDom.window.document.querySelector('.invocation'); n++) await new Promise(resolve => setTimeout(resolve, 20));
    assert.ok(pagedDom.window.document.querySelector('.invocation')?.textContent.includes('older-call'));
    assert.equal(pagedDom.window.document.querySelector('.session-picker summary').textContent.trim(), 'Selected session');
  } finally { pagedDom?.window.close(); await pagedApp?.close(); await rm(pagedDirectory, { recursive: true, force: true }); }
} finally {
  for (const id of intervals) dom?.window.clearInterval(id);
  await new Promise(resolve => setTimeout(resolve, 50));
  dom?.window.close(); await app?.close(); await rm(directory, { recursive: true, force: true });
}
